version: '3.7'
services:
  app:
    image: node:16
    ports: 
    - 3000:3000
    working_dir: /dev/git_api_vis
    volumes:
      - .:/dev/git_api_vis
    command: >
              sh -c "npm i && npm start"